version: '3.5'

services:
  openldap:
    image: nugaon/kerberos-with-ldap
    ports:
      # LDAP
      - 389:389
      - 636:636
      # kadmin server
      - 749:749
      # Kerberos v5
      - 88:88
      - 88:88/udp
    container_name: openldap
    # `--copy-service` prevents ldif files from being overwritten after subsitution. Add ` --loglevel debug` for debug
    # command: --copy-service --loglevel debug
    volumes:
      - vol-openldap-ldap:/var/lib/ldap
      - vol-openldap-slapd:/etc/ldap/slapd.d
      - ./keytabs:/etc/keytabs
    networks:
      alfresco-network:
        ipv4_address: 192.168.55.5

  alfresco:
      # image: alfresco/alfresco-content-repository:6.2.2
      container_name: alfresco
      hostname: alfresco
      build:
        context: ./alfresco
#      extra_hosts:
#        - "dc01.example.com:192.168.100.25"
#        - "dc01:192.168.100.25"
      environment:
        JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE

                -Dtransform.service.enabled=true
                -Dtransform.service.url=http://transform-router:8095
                -Dsfs.url=http://shared-file-store:8099/

                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/

                -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
                -Djodconverter.url=http://transform-core-aio:8090/
                -Dimg.url=http://transform-core-aio:8090/
                -Dtika.url=http://transform-core-aio:8090/
                -Dtransform.misc.url=http://transform-core-aio:8090/

                -Dcsrf.filter.enabled=false
                -Ddsync.service.uris=http://localhost:9090/alfresco
                -Xms1500m -Xmx1500m

                -Dldap.authentication.allowGuestLogin=false
                -Dldap.authentication.userNameFormat=%s@example.com
                -Dldap.authentication.java.naming.provider.url=ldap://192.168.55.5:389
                -Dldap.authentication.defaultAdministratorUserNames=joe.bloggs,vagrant
                -Dldap.authentication.active=false

                -Dsynchronization.autoCreatePeopleOnLogin=false
                -Dldap.synchronization.active=true

                -Dldap.synchronization.java.naming.security.principal=alfresco.ldap@example.com
                -Dldap.synchronization.java.naming.security.credentials=C0mplexPassword
                -Dldap.synchronization.groupSearchBase=OU=Alfresco-Groups,DC=example,DC=org
                -Dldap.synchronization.userSearchBase=OU=Alfresco-Users,DC=example,DC=org

                -Dkerberos.authentication.realm=EXAMPLE.COM
                -Dkerberos.authentication.user.configEntryName=Alfresco
                -Dkerberos.authentication.defaultAdministratorUserNames=joe.bloggs,vagrant
                -Dkerberos.authentication.http.configEntryName=AlfrescoHTTP
                -Dkerberos.authentication.http.password=HeyH0Password
                -Dkerberos.authentication.sso.enabled=true

                -Dauthentication.chain=kerberos1:kerberos,alfrescoNtlm1:alfrescoNtlm,ldap1:ldap-ad
                "
      volumes:
          # For sharing keytab files from Kerberos
          - ./keytabs:/etc
      depends_on:
        - openldap
      links:
        - openldap
      restart: on-failure # will restart until it's success
      networks:
        alfresco-network:
          ipv4_address: 192.168.55.10

  transform-router:
      image: quay.io/alfresco/alfresco-transform-router:1.3.2
      environment:
        JAVA_OPTS: " -Xms256m -Xmx512m"
        ACTIVEMQ_URL: "nio://activemq:61616"

        CORE_AIO_URL : "http://transform-core-aio:8090"

        FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
      ports:
        - 8095:8095
      links:
        - activemq
      networks:
        alfresco-network:

  transform-core-aio:
      image: alfresco/alfresco-transform-core-aio:2.3.10
      environment:
        JAVA_OPTS: " -Xms256m -Xmx1536m"
        ACTIVEMQ_URL: "nio://activemq:61616"
        FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
      ports:
        - 8090:8090
      links:
        - activemq
      networks:
        alfresco-network:

  shared-file-store:
      image: alfresco/alfresco-shared-file-store:0.13.0
      environment:
        JAVA_OPTS: " -Xms256m -Xmx512m"
        scheduler.content.age.millis: 86400000
        scheduler.cleanup.interval: 86400000
      ports:
        - 8099:8099
      volumes:
        - shared-file-store-volume:/tmp/Alfresco/sfs
      networks:
        alfresco-network:

  postgres:
      image: postgres:11.7
      environment:
        - POSTGRES_PASSWORD=alfresco
        - POSTGRES_USER=alfresco
        - POSTGRES_DB=alfresco
      command: postgres -c max_connections=300 -c log_min_messages=LOG
      ports:
        - 5432:5432
      networks:
        alfresco-network:

  solr6:
      image: alfresco/alfresco-search-services:2.0.1
      environment:
        #Solr needs to know how to register itself with Alfresco
        - SOLR_ALFRESCO_HOST=alfresco
        - SOLR_ALFRESCO_PORT=8080
        #Alfresco needs to know how to call solr
        - SOLR_SOLR_HOST=solr6
        - SOLR_SOLR_PORT=8983
        #Create the default alfresco and archive cores
        - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
        #HTTP by default
        - ALFRESCO_SECURE_COMMS=none
        - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
      ports:
        - 8083:8983 #Browser port
      networks:
        alfresco-network:

  activemq:
      image: alfresco/alfresco-activemq:5.16.1
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP
      networks:
        alfresco-network:

  digital-workspace:
      image: quay.io/alfresco/alfresco-digital-workspace:1.6.0
      environment:
        BASE_PATH: ./
      networks:
        alfresco-network:

  proxy:
      image: alfresco/alfresco-acs-nginx:3.0.1
      depends_on:
        - alfresco
        - digital-workspace
      ports:
        - 8080:8080
      links:
        - digital-workspace
        - alfresco

networks:
  alfresco-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24

volumes:
  vol-openldap-ldap:
  vol-openldap-slapd:
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
