version: '3.5'

services:
  openldap:
    image: osixia/openldap
    ports:
      - 389:389
      - 636:636
    env_file:
      - ./openldap/openldap.env
    container_name: openldap
    command: --copy-service --loglevel debug
    volumes:
      - ./openldap/00-kerberos.ldif:/container/service/slapd/assets/config/bootstrap/ldif/00-kerberos.ldif
      - ./openldap/02-security.ldif:/container/service/slapd/assets/config/bootstrap/ldif/02-security.ldif
      - ./openldap/05-index.ldif:/container/service/slapd/assets/config/bootstrap/ldif/05-index.ldif
      - ./openldap/ldap-init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
      - vol-openldap-ldap:/var/lib/ldap
      - vol-openldap-slapd:/etc/ldap/slapd.d
    networks:
      alfresco-network:

  kerberos:
    image: nugaon/kerberos-with-ldap
    container_name: kerberos
    environment:
      LDAP_URL: "ldap://openldap:389"
    depends_on:
      - openldap
    ports:
      - 88:88
      - 464:464
      - 749:749
    networks:
      alfresco-network:
        ipv4_address: 192.168.55.10

  alfresco:
      # image: alfresco/alfresco-content-repository:6.2.2
      container_name: alfresco
      hostname: alfresco
      build:
        context: ./alfresco
      extra_hosts:
        - "example.com:192.168.55.10"
      environment:
        JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=80
                -Dalfresco.host=localhost
                -Dalfresco.port=80
                -Daos.baseUrlOverwrite=http://localhost:80/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE

                -Dtransform.service.enabled=true
                -Dtransform.service.url=http://transform-router:8095
                -Dsfs.url=http://shared-file-store:8099/

                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/

                -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
                -Djodconverter.url=http://transform-core-aio:8090/
                -Dimg.url=http://transform-core-aio:8090/
                -Dtika.url=http://transform-core-aio:8090/
                -Dtransform.misc.url=http://transform-core-aio:8090/

                -Dcsrf.filter.enabled=false
                -Ddsync.service.uris=http://localhost:9090/alfresco
                -Xms1500m -Xmx1500m

                -Dldap.authentication.allowGuestLogin=false
                -Dldap.authentication.userNameFormat=%s@example.com
                -Dldap.authentication.java.naming.provider.url=ldap://openldap:389
                -Dldap.authentication.defaultAdministratorUserNames=administrator,admin,adminAlfresco,administrador
                -Dldap.authentication.active=false

                -Dsynchronization.autoCreatePeopleOnLogin=false
                -Dldap.synchronization.active=true

                -Dldap.synchronization.java.naming.security.principal=cn=admin,dc=example,dc=com
                -Dldap.synchronization.java.naming.security.credentials=admin
                -Dldap.synchronization.groupSearchBase=\"dc\\=example,dc\\=com\"
                -Dldap.synchronization.userIdAttributeName=uid
                -Dldap.synchronization.userFirstNameAttributeName=cn
                -Dldap.synchronization.userLastNameAttributeName=sn
                -Dldap.synchronization.userEmailAttributeName=mail
                -Dldap.synchronization.personQuery=\"(objectclass\\=person)\"
                -Dldap.synchronization.userSearchBase=\"dc=example,dc=com\"

                -Dkerberos.authentication.realm=EXAMPLE.COM
                -Dkerberos.authentication.user.configEntryName=Alfresco
                -Dkerberos.authentication.defaultAdministratorUserNames=administrator,admin,adminAlfresco,administrador
                -Dkerberos.authentication.http.configEntryName=AlfrescoHTTP
                -Dkerberos.authentication.http.password=password
                -Dkerberos.authentication.sso.enabled=true

                -Dauthentication.chain=kerberos1:kerberos,alfrescoNtlm1:alfrescoNtlm,ldap1:ldap-ad
                "
      depends_on:
        - openldap
      links:
        - openldap
      restart: on-failure # will restart until it's success
      networks:
        alfresco-network:

  transform-router:
      image: quay.io/alfresco/alfresco-transform-router:1.3.2
      environment:
        JAVA_OPTS: " -Xms256m -Xmx512m"
        ACTIVEMQ_URL: "nio://activemq:61616"

        CORE_AIO_URL : "http://transform-core-aio:8090"

        FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
      ports:
        - 8095:8095
      links:
        - activemq
      networks:
        alfresco-network:

  transform-core-aio:
      image: alfresco/alfresco-transform-core-aio:2.3.10
      environment:
        JAVA_OPTS: " -Xms256m -Xmx1536m"
        ACTIVEMQ_URL: "nio://activemq:61616"
        FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
      ports:
        - 8090:8090
      links:
        - activemq
      networks:
        alfresco-network:

  shared-file-store:
      image: alfresco/alfresco-shared-file-store:0.13.0
      environment:
        JAVA_OPTS: " -Xms256m -Xmx512m"
        scheduler.content.age.millis: 86400000
        scheduler.cleanup.interval: 86400000
      ports:
        - 8099:8099
      volumes:
        - shared-file-store-volume:/tmp/Alfresco/sfs
      networks:
        alfresco-network:

  postgres:
      image: postgres:11.7
      environment:
        - POSTGRES_PASSWORD=alfresco
        - POSTGRES_USER=alfresco
        - POSTGRES_DB=alfresco
      command: postgres -c max_connections=300 -c log_min_messages=LOG
      ports:
        - 5432:5432
      networks:
        alfresco-network:

  solr6:
      image: alfresco/alfresco-search-services:2.0.1
      environment:
        #Solr needs to know how to register itself with Alfresco
        - SOLR_ALFRESCO_HOST=alfresco
        - SOLR_ALFRESCO_PORT=80
        #Alfresco needs to know how to call solr
        - SOLR_SOLR_HOST=solr6
        - SOLR_SOLR_PORT=8983
        #Create the default alfresco and archive cores
        - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
        #HTTP by default
        - ALFRESCO_SECURE_COMMS=none
        - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
      ports:
        - 8083:8983 #Browser port
      networks:
        alfresco-network:

  activemq:
      image: alfresco/alfresco-activemq:5.16.1
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP
      networks:
        alfresco-network:

  workspace:
      image: dhrn/demo-shell:latest
      container_name: workspace
      hostname: workspace
      environment:
        BASE_PATH: ./
        APP_CONFIG_AUTH_TYPE: ECM
      networks:
        alfresco-network:

  proxy:
      image: alfresco/alfresco-acs-nginx:3.0.1
      container_name: proxy
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - alfresco
        - workspace
      ports:
        - 80:80
      links:
        - workspace
        - alfresco
      networks:
        alfresco-network:

networks:
  alfresco-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24

volumes:
  vol-openldap-ldap:
  vol-openldap-slapd:
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
